spring.application.name=backend
# MongoDB connection
#spring.mongodb.host=localhost
#spring.mongodb.port=27017
#spring.mongodb.database=moji_db

# Nếu dùng MongoDB Atlas (cloud)
# spring.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.mongodb.net/moji_db
mongodb+srv://duclahoa98_db_user:<db_password>@cluster0.1bwsdcr.mongodb.net/?appName=Cluster0

# Server port
server.port=8080
