spring.application.name=backend

# MongoDB connection
#spring.mongodb.host=localhost
#spring.mongodb.port=27017
#spring.mongodb.database=moji_db

# Nếu dùng MongoDB Atlas (cloud)
# spring.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.mongodb.net/moji_db

spring.datasource.url=jdbc:mysql://localhost:3306/moji?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=cmcglobal@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server port
server.port=5001
